/* eslint-disable implicit-arrow-linebreak */

export const TRAIT_IDS = [
  "aegis",
  "ember",
  "wild",
  "rift",
  "clockwork",
  "vanguard",
  "ranger",
  "mystic",
  "brawler",
  "assassin",
  "sui_forms",
] as const;

export type TraitId = (typeof TRAIT_IDS)[number];

export const SHOP_UNIT_IDS = [
  // 1 费
  "sun_guard",
  "ember_blade",
  "gale_archer",
  "rift_stalker",
  "cog_scribe",
  "mossback",
  "sui",
  // 2 费
  "rift_brawler",
  "sui_blue",
  "shiori",
  "spark_mage",
  "clock_gunner",
  "dawn_duelist",
  "grove_mender",
  "cinder_ram",
  // 3 费
  "brass_colossus",
  "ash_dancer",
  "thorn_brute",
  "void_oracle",
  "gear_sniper",
  "shade_reaver",
  "sui_bird",
  "sui_flower",
  "yua",
  // 4 费
  "sun_phoenix",
  "sui_cat",
  "nagisa",
  "prism_sage",
  "moonfang",
  "rift_warden",
  "iron_dervish",
  "siege_walker",
  // 5 费
  "dawn_sovereign",
  "solar_champion",
  "inferno_witch",
  "sky_drake",
  "void_reaper",
  "chrono_titan",
  "biscuit_sui",
] as const;

export type ShopUnitId = (typeof SHOP_UNIT_IDS)[number];
export type UnitId = ShopUnitId | "rift_tyrant";

export type StarterId = "bastion" | "blaze" | "echo";

export type AugmentId =
  | "tempered"
  | "overclock"
  | "sharp_edge"
  | "momentum"
  | "triage"
  | "payday"
  | "execution"
  | "second_wind";

export interface UnitDefinition {
  id: UnitId;
  name: string;
  title: string;
  glyph: string;
  color: string;
  accent: string;
  tier: 1 | 2 | 3 | 4 | 5;
  cost: number;
  traits: TraitId[];
  hp: number;
  attack: number;
  armor: number;
  range: number;
  attackInterval: number;
  moveSpeed: number;
  abilityName: string;
  abilityDescription: string;
  portrait?: string;
  portraitFocus?: "top" | "center";
  shop: boolean;
}

export interface TraitDefinition {
  id: TraitId;
  name: string;
  family: "阵营" | "职业";
  color: string;
  thresholds: readonly [2, 4, 6];
  description: string;
  bonuses: readonly [string, string, string];
}

export interface StarterDefinition {
  id: StarterId;
  name: string;
  subtitle: string;
  description: string;
  unit: ShopUnitId;
  color: string;
}

export interface AugmentDefinition {
  id: AugmentId;
  name: string;
  kicker: string;
  description: string;
  color: string;
}

export interface WaveUnit {
  id: UnitId;
  star?: 1 | 2 | 3;
}

export interface WaveDefinition {
  round: number;
  name: string;
  tag: "normal" | "elite" | "boss";
  description: string;
  modifier: number;
  units: WaveUnit[];
}

export const TRAITS: Record<TraitId, TraitDefinition> = {
  aegis: {
    id: "aegis",
    name: "曜甲",
    family: "阵营",
    color: "#66d7ff",
    thresholds: [2, 4, 6],
    description: "曜甲成员坚固，并在高阶时为全队提供开战护盾。",
    bonuses: [
      "曜甲单位 +12 护甲、+7% 最大生命",
      "曜甲单位 +25/+14%；全体友军开战获 8% 最大生命护盾",
      "曜甲单位 +42/+23%；全体友军开战获 16% 最大生命护盾",
    ],
  },
  ember: {
    id: "ember",
    name: "余烬",
    family: "阵营",
    color: "#ff7657",
    thresholds: [2, 4, 6],
    description: "余烬成员擅长灼烧，高阶会让远程友军也携带火力。",
    bonuses: [
      "余烬单位普攻灼烧 35% 攻击力",
      "余烬 65%；所有远程友军普攻灼烧 25% 攻击力",
      "余烬 105%；所有远程友军普攻灼烧 50% 攻击力",
    ],
  },
  wild: {
    id: "wild",
    name: "荒灵",
    family: "阵营",
    color: "#70e1a0",
    thresholds: [2, 4, 6],
    description: "荒灵成员吸血，高阶将生机赋予所有近战友军。",
    bonuses: [
      "荒灵单位获得 8% 吸血",
      "荒灵 15%；所有近战友军获得 6% 吸血",
      "荒灵 24%；所有近战友军获得 12% 吸血",
    ],
  },
  rift: {
    id: "rift",
    name: "裂隙",
    family: "阵营",
    color: "#c08bff",
    thresholds: [2, 4, 6],
    description: "裂隙成员终结受伤目标，高阶会让全队协同收割。",
    bonuses: [
      "裂隙单位对半血目标 +15% 伤害",
      "裂隙 +32%；全体友军对半血目标 +10% 伤害",
      "裂隙 +55%；全体友军对半血目标 +20% 伤害",
    ],
  },
  clockwork: {
    id: "clockwork",
    name: "机巧",
    family: "阵营",
    color: "#e5bf68",
    thresholds: [2, 4, 6],
    description: "机巧成员高速蓄能，高阶为远程友军提供火力支援。",
    bonuses: [
      "机巧单位 +10% 攻速、每击 +4 能量",
      "机巧 +22%/+8；所有远程友军 +10% 攻速",
      "机巧 +38%/+14；所有远程友军 +22% 攻速、每击 +4 能量",
    ],
  },
  vanguard: {
    id: "vanguard",
    name: "先锋",
    family: "职业",
    color: "#819eff",
    thresholds: [2, 4, 6],
    description: "先锋成员守住前线，高阶为所有近战友军提供防护。",
    bonuses: [
      "先锋单位 +12% 生命、+8 护甲",
      "先锋 +25%/+18；所有近战友军 +8% 生命、+6 护甲",
      "先锋 +42%/+32；所有近战友军 +16% 生命、+12 护甲",
    ],
  },
  ranger: {
    id: "ranger",
    name: "游击",
    family: "职业",
    color: "#f2d15e",
    thresholds: [2, 4, 6],
    description: "游击成员擅长速射，高阶会加速所有远程友军。",
    bonuses: [
      "游击单位 +12% 攻速",
      "游击 +26%；所有远程友军 +15% 攻速",
      "游击 +45%；所有远程友军 +30% 攻速",
    ],
  },
  mystic: {
    id: "mystic",
    name: "秘术",
    family: "职业",
    color: "#de87ff",
    thresholds: [2, 4, 6],
    description: "秘术成员先手施法，高阶会为全队注入能量。",
    bonuses: [
      "秘术单位开战 +20 能量",
      "秘术开战 +45、施法返还 8；全体友军开战 +10 能量",
      "秘术开战 +70、施法返还 15；全体友军开战 +22 能量",
    ],
  },
  brawler: {
    id: "brawler",
    name: "斗阵",
    family: "职业",
    color: "#ffae57",
    thresholds: [2, 4, 6],
    description: "斗阵成员重击前线，高阶会强化所有近战友军。",
    bonuses: [
      "斗阵单位 +12% 攻击力",
      "斗阵 +26%；所有近战友军 +10% 攻击力",
      "斗阵 +45%；所有近战友军 +20% 攻击力",
    ],
  },
  assassin: {
    id: "assassin",
    name: "夜袭",
    family: "职业",
    color: "#ff6fae",
    thresholds: [2, 4, 6],
    description: "夜袭成员切入后排，高阶会提高远程友军的暴击。",
    bonuses: [
      "夜袭单位跃向后排、获得 15% 暴击率",
      "夜袭 30% 暴击；所有远程友军 +12% 暴击率",
      "夜袭 50% 暴击；所有远程友军 +25% 暴击率",
    ],
  },
  sui_forms: {
    id: "sui_forms",
    name: "早鸟有饼",
    family: "阵营",
    color: "#f2a7d4",
    thresholds: [2, 4, 6],
    description: "岁己形态围绕早起、小鸟与饼干互相打气：先手积蓄能量，持续获得续航。",
    bonuses: [
      "岁己单位获得 8% 吸血、开战 +10 能量",
      "岁己单位 15% 吸血、+22 能量；全体友军开战 +8 能量",
      "岁己单位 24% 吸血、+35 能量；全体友军开战 +18 能量",
    ],
  },
};

export const traitLevelForCount = (trait: TraitDefinition, count: number) =>
  trait.thresholds.filter((threshold) => count >= threshold).length;

const unit = (definition: UnitDefinition) => definition;

export const UNIT_DEFS: Record<UnitId, UnitDefinition> = {
  // 1 费：可靠的构筑零件，每个都能明确指向一条阵容路线。
  sun_guard: unit({
    id: "sun_guard",
    name: "曜盾卫士",
    title: "坚守前线",
    glyph: "盾",
    color: "#245f80",
    accent: "#7de2ff",
    tier: 1,
    cost: 1,
    traits: ["aegis", "vanguard"],
    hp: 245,
    attack: 16,
    armor: 30,
    range: 48,
    attackInterval: 1.12,
    moveSpeed: 52,
    abilityName: "折光壁垒",
    abilityDescription: "获得护盾，震击并短暂眩晕当前目标。",
    shop: true,
  }),
  ember_blade: unit({
    id: "ember_blade",
    name: "熔火刃",
    title: "近战爆发",
    glyph: "焰",
    color: "#7b2f2b",
    accent: "#ff8a5c",
    tier: 1,
    cost: 1,
    traits: ["ember", "brawler"],
    hp: 178,
    attack: 25,
    armor: 12,
    range: 50,
    attackInterval: 0.92,
    moveSpeed: 64,
    abilityName: "熔断横斩",
    abilityDescription: "横扫目标周围的敌人，并施加灼烧。",
    shop: true,
  }),
  gale_archer: unit({
    id: "gale_archer",
    name: "岚羽",
    title: "高速点射",
    glyph: "岚",
    color: "#245e4e",
    accent: "#7ef0bb",
    tier: 1,
    cost: 1,
    traits: ["wild", "ranger"],
    hp: 132,
    attack: 21,
    armor: 6,
    range: 225,
    attackInterval: 0.84,
    moveSpeed: 58,
    abilityName: "追风三矢",
    abilityDescription: "连续射出三支箭，优先追击残血敌人。",
    shop: true,
  }),
  rift_stalker: unit({
    id: "rift_stalker",
    name: "隙影斥候",
    title: "后排骚扰",
    glyph: "隙",
    color: "#493464",
    accent: "#c99cff",
    tier: 1,
    cost: 1,
    traits: ["rift", "assassin"],
    hp: 146,
    attack: 23,
    armor: 8,
    range: 48,
    attackInterval: 0.88,
    moveSpeed: 78,
    abilityName: "影隙突刺",
    abilityDescription: "闪至最虚弱的敌人身旁突刺，并获得小额护盾。",
    shop: true,
  }),
  cog_scribe: unit({
    id: "cog_scribe",
    name: "齿轮学徒",
    title: "能量干扰",
    glyph: "轮",
    color: "#4d4936",
    accent: "#e8ca75",
    tier: 1,
    cost: 1,
    traits: ["clockwork", "mystic"],
    hp: 138,
    attack: 18,
    armor: 8,
    range: 190,
    attackInterval: 1.08,
    moveSpeed: 48,
    abilityName: "回转电弧",
    abilityDescription: "电击两个敌人并削减其能量。",
    shop: true,
  }),
  mossback: unit({
    id: "mossback",
    name: "苔甲幼兽",
    title: "群体庇护",
    glyph: "苔",
    color: "#315b40",
    accent: "#80d792",
    tier: 1,
    cost: 1,
    traits: ["wild", "vanguard"],
    hp: 255,
    attack: 15,
    armor: 24,
    range: 48,
    attackInterval: 1.2,
    moveSpeed: 45,
    abilityName: "共生甲壳",
    abilityDescription: "治疗自己，并为最虚弱的友军提供护盾。",
    shop: true,
  }),
  sui: unit({
    id: "sui",
    name: "小红帽岁己",
    title: "早起失败的前排",
    glyph: "红",
    color: "#8f3f4e",
    accent: "#ffabb5",
    tier: 1,
    cost: 1,
    traits: ["sui_forms", "vanguard"],
    hp: 244,
    attack: 17,
    armor: 24,
    range: 48,
    attackInterval: 1.12,
    moveSpeed: 52,
    abilityName: "大家在吗？",
    abilityDescription: "呼喊大家在吗，获得护盾，震击并短暂眩晕当前目标。",
    portrait: "/images/materials/red/1d5ad005aff0b4b648a0f1ef6b8d0cd71954091502.png",
    portraitFocus: "top",
    shop: true,
  }),

  // 2 费：开始提供反后排、控制和续航等战术答案。
  rift_brawler: unit({
    id: "rift_brawler",
    name: "裂隙猎手",
    title: "残血收割",
    glyph: "猎",
    color: "#4c3c72",
    accent: "#c4a1ff",
    tier: 2,
    cost: 2,
    traits: ["rift", "brawler"],
    hp: 205,
    attack: 29,
    armor: 14,
    range: 52,
    attackInterval: 1.02,
    moveSpeed: 76,
    abilityName: "相位猎杀",
    abilityDescription: "跃向生命比例最低的敌人，重创残血目标。",
    shop: true,
  }),
  spark_mage: unit({
    id: "spark_mage",
    name: "星火术士",
    title: "范围轰击",
    glyph: "星",
    color: "#593270",
    accent: "#e7a3ff",
    tier: 2,
    cost: 2,
    traits: ["ember", "mystic"],
    hp: 142,
    attack: 21,
    armor: 6,
    range: 205,
    attackInterval: 1.18,
    moveSpeed: 50,
    abilityName: "坠星火",
    abilityDescription: "轰击敌人最密集的区域，造成范围伤害与灼烧。",
    shop: true,
  }),
  clock_gunner: unit({
    id: "clock_gunner",
    name: "机巧枪手",
    title: "直线穿透",
    glyph: "铳",
    color: "#36566f",
    accent: "#92d7ff",
    tier: 2,
    cost: 2,
    traits: ["clockwork", "ranger"],
    hp: 158,
    attack: 22,
    armor: 12,
    range: 245,
    attackInterval: 0.72,
    moveSpeed: 48,
    abilityName: "超载贯射",
    abilityDescription: "发射贯穿战场的高能弹，惩罚站成一线的敌人。",
    shop: true,
  }),
  dawn_duelist: unit({
    id: "dawn_duelist",
    name: "晨锋决斗家",
    title: "锁定后排",
    glyph: "锋",
    color: "#315b78",
    accent: "#9ee8ff",
    tier: 2,
    cost: 2,
    traits: ["aegis", "assassin"],
    hp: 176,
    attack: 27,
    armor: 16,
    range: 50,
    attackInterval: 0.82,
    moveSpeed: 82,
    abilityName: "破晓决斗",
    abilityDescription: "突进至最远敌人，重击并短暂眩晕。",
    shop: true,
  }),
  grove_mender: unit({
    id: "grove_mender",
    name: "森灵祭司",
    title: "战地治疗",
    glyph: "愈",
    color: "#28644b",
    accent: "#79f2ad",
    tier: 2,
    cost: 2,
    traits: ["wild", "mystic"],
    hp: 158,
    attack: 16,
    armor: 9,
    range: 190,
    attackInterval: 1.22,
    moveSpeed: 46,
    abilityName: "生息回响",
    abilityDescription: "治疗生命比例最低的两名友军。",
    shop: true,
  }),
  cinder_ram: unit({
    id: "cinder_ram",
    name: "烬角冲阵者",
    title: "开团控制",
    glyph: "角",
    color: "#71382f",
    accent: "#ff9a64",
    tier: 2,
    cost: 2,
    traits: ["ember", "vanguard"],
    hp: 278,
    attack: 20,
    armor: 25,
    range: 50,
    attackInterval: 1.16,
    moveSpeed: 68,
    abilityName: "赤角冲锋",
    abilityDescription: "冲进敌群，震晕并灼烧落点附近的敌人。",
    shop: true,
  }),
  sui_blue: unit({
    id: "sui_blue",
    name: "小蓝帽岁己",
    title: "后排补刀",
    glyph: "蓝",
    color: "#3a5d94",
    accent: "#92c8ff",
    tier: 2,
    cost: 2,
    traits: ["sui_forms", "ranger"],
    hp: 148,
    attack: 25,
    armor: 8,
    range: 235,
    attackInterval: 0.82,
    moveSpeed: 58,
    abilityName: "闪购闪购",
    abilityDescription: "连续射出三道闪购，优先追击残血敌人。",
    portrait: "/images/materials/blue/5a2bcc519c33a2213134bdc196799d041954091502.png",
    portraitFocus: "top",
    shop: true,
  }),
  shiori: unit({
    id: "shiori",
    name: "栞栞",
    title: "折页护符",
    glyph: "栞",
    color: "#6c7599",
    accent: "#c3cfff",
    tier: 2,
    cost: 2,
    traits: ["aegis", "mystic"],
    hp: 164,
    attack: 20,
    armor: 11,
    range: 205,
    attackInterval: 1.08,
    moveSpeed: 50,
    abilityName: "折页护符",
    abilityDescription: "为两名最低生命比例的友军提供护盾。",
    portrait: "/images/livers/shiori.png",
    portraitFocus: "top",
    shop: true,
  }),

  // 3 费：阵容中期核心，技能形态开始明显改变站位价值。
  brass_colossus: unit({
    id: "brass_colossus",
    name: "铜墙巨像",
    title: "群体控制",
    glyph: "岳",
    color: "#5f5435",
    accent: "#f2d276",
    tier: 3,
    cost: 3,
    traits: ["aegis", "vanguard"],
    hp: 350,
    attack: 22,
    armor: 38,
    range: 52,
    attackInterval: 1.32,
    moveSpeed: 38,
    abilityName: "山崩震荡",
    abilityDescription: "震晕周围敌人并获得护盾。",
    shop: true,
  }),
  ash_dancer: unit({
    id: "ash_dancer",
    name: "灰烬舞者",
    title: "多段切入",
    glyph: "舞",
    color: "#75334a",
    accent: "#ff829c",
    tier: 3,
    cost: 3,
    traits: ["ember", "assassin"],
    hp: 190,
    attack: 32,
    armor: 13,
    range: 50,
    attackInterval: 0.76,
    moveSpeed: 88,
    abilityName: "烬步连舞",
    abilityDescription: "穿梭攻击三名敌人，并沿途留下灼烧。",
    shop: true,
  }),
  thorn_brute: unit({
    id: "thorn_brute",
    name: "棘原蛮王",
    title: "吸血旋击",
    glyph: "棘",
    color: "#3b6547",
    accent: "#8be59c",
    tier: 3,
    cost: 3,
    traits: ["wild", "brawler"],
    hp: 286,
    attack: 31,
    armor: 20,
    range: 54,
    attackInterval: 0.98,
    moveSpeed: 60,
    abilityName: "荆棘风暴",
    abilityDescription: "横扫附近敌人，每命中一名敌人都会恢复生命。",
    shop: true,
  }),
  void_oracle: unit({
    id: "void_oracle",
    name: "虚界先知",
    title: "克制高血量",
    glyph: "卜",
    color: "#4e3569",
    accent: "#d0a0ff",
    tier: 3,
    cost: 3,
    traits: ["rift", "mystic"],
    hp: 172,
    attack: 25,
    armor: 10,
    range: 215,
    attackInterval: 1.12,
    moveSpeed: 50,
    abilityName: "虚蚀预言",
    abilityDescription: "诅咒最大生命最高的敌人，附加其最大生命伤害。",
    shop: true,
  }),
  gear_sniper: unit({
    id: "gear_sniper",
    name: "发条狙击手",
    title: "超远单点",
    glyph: "狙",
    color: "#47576a",
    accent: "#b4dcff",
    tier: 3,
    cost: 3,
    traits: ["clockwork", "ranger"],
    hp: 166,
    attack: 34,
    armor: 9,
    range: 285,
    attackInterval: 1.05,
    moveSpeed: 42,
    abilityName: "校准绝响",
    abilityDescription: "蓄力狙击最远敌人，造成高额单体伤害。",
    shop: true,
  }),
  shade_reaver: unit({
    id: "shade_reaver",
    name: "黯隙收割者",
    title: "技能重置",
    glyph: "黯",
    color: "#3e294f",
    accent: "#b96fff",
    tier: 3,
    cost: 3,
    traits: ["rift", "assassin"],
    hp: 182,
    attack: 33,
    armor: 12,
    range: 48,
    attackInterval: 0.86,
    moveSpeed: 92,
    abilityName: "黯影处决",
    abilityDescription: "重创最虚弱的敌人；击杀后立即回复大量能量。",
    shop: true,
  }),
  sui_bird: unit({
    id: "sui_bird",
    name: "小岁鸟",
    title: "鸟本体援护",
    glyph: "鸟",
    color: "#4d7494",
    accent: "#f7d77c",
    tier: 3,
    cost: 3,
    traits: ["sui_forms", "mystic"],
    hp: 188,
    attack: 27,
    armor: 11,
    range: 220,
    attackInterval: 1.02,
    moveSpeed: 68,
    abilityName: "小鸟归巢",
    abilityDescription: "飞向最虚弱的友军，为其治疗、护盾并以羽流伤害附近敌人。",
    portrait: "/images/materials/bird/岁己_小鸟跳静态图.png",
    shop: true,
  }),
  sui_flower: unit({
    id: "sui_flower",
    name: "小花帽岁己",
    title: "辣味控场",
    glyph: "花",
    color: "#a15282",
    accent: "#f6a8d4",
    tier: 3,
    cost: 3,
    traits: ["sui_forms", "mystic"],
    hp: 184,
    attack: 27,
    armor: 12,
    range: 205,
    attackInterval: 1.1,
    moveSpeed: 52,
    abilityName: "火烧云",
    abilityDescription: "向敌人最密集的区域降下火烧云，造成范围伤害与眩晕。",
    portrait: "/images/materials/flower/622764c8178eb3f6411da20a917cc0321954091502.png",
    portraitFocus: "top",
    shop: true,
  }),
  yua: unit({
    id: "yua",
    name: "悠亚",
    title: "炽光点射",
    glyph: "悠",
    color: "#9b6345",
    accent: "#ffc28a",
    tier: 3,
    cost: 3,
    traits: ["ember", "ranger"],
    hp: 172,
    attack: 32,
    armor: 10,
    range: 250,
    attackInterval: 0.78,
    moveSpeed: 56,
    abilityName: "炽光点射",
    abilityDescription: "向低生命敌人三连点射，并施加灼烧。",
    portrait: "/images/livers/yua.png",
    portraitFocus: "top",
    shop: true,
  }),

  // 4 费：可以围绕其单独建立阵容的核心单位。
  sun_phoenix: unit({
    id: "sun_phoenix",
    name: "焚天鸟",
    title: "全场灼烧",
    glyph: "凰",
    color: "#7b3e2c",
    accent: "#ffd166",
    tier: 4,
    cost: 4,
    traits: ["ember", "ranger"],
    hp: 190,
    attack: 31,
    armor: 12,
    range: 225,
    attackInterval: 0.78,
    moveSpeed: 64,
    abilityName: "燎原羽雨",
    abilityDescription: "灼烧全部敌人，并恢复自身生命。",
    shop: true,
  }),
  prism_sage: unit({
    id: "prism_sage",
    name: "棱光贤者",
    title: "全队庇护",
    glyph: "棱",
    color: "#416580",
    accent: "#a9ecff",
    tier: 4,
    cost: 4,
    traits: ["aegis", "mystic"],
    hp: 205,
    attack: 25,
    armor: 18,
    range: 210,
    attackInterval: 1.08,
    moveSpeed: 48,
    abilityName: "万华折光",
    abilityDescription: "治疗全队、赋予护盾，并为友军补充能量。",
    shop: true,
  }),
  moonfang: unit({
    id: "moonfang",
    name: "月蚀牙",
    title: "后排连斩",
    glyph: "牙",
    color: "#315846",
    accent: "#8ff0c0",
    tier: 4,
    cost: 4,
    traits: ["wild", "assassin"],
    hp: 222,
    attack: 38,
    armor: 16,
    range: 50,
    attackInterval: 0.7,
    moveSpeed: 96,
    abilityName: "月下狩猎",
    abilityDescription: "扑向最远敌人连续撕咬，并恢复造成伤害的生命。",
    shop: true,
  }),
  rift_warden: unit({
    id: "rift_warden",
    name: "界门守望者",
    title: "团队护盾",
    glyph: "门",
    color: "#44365e",
    accent: "#c39cff",
    tier: 4,
    cost: 4,
    traits: ["rift", "vanguard"],
    hp: 405,
    attack: 27,
    armor: 34,
    range: 55,
    attackInterval: 1.24,
    moveSpeed: 42,
    abilityName: "界门封锁",
    abilityDescription: "为全队提供护盾，并震晕身边敌人。",
    shop: true,
  }),
  iron_dervish: unit({
    id: "iron_dervish",
    name: "铁律旋刃",
    title: "持续范围伤害",
    glyph: "旋",
    color: "#5a513c",
    accent: "#e7c66f",
    tier: 4,
    cost: 4,
    traits: ["clockwork", "brawler"],
    hp: 318,
    attack: 36,
    armor: 26,
    range: 58,
    attackInterval: 0.74,
    moveSpeed: 66,
    abilityName: "齿轮圆舞",
    abilityDescription: "高速旋转切割附近敌人，并立刻重置普攻。",
    shop: true,
  }),
  siege_walker: unit({
    id: "siege_walker",
    name: "攻城履带",
    title: "重炮控制",
    glyph: "炮",
    color: "#4a5260",
    accent: "#f0ca78",
    tier: 4,
    cost: 4,
    traits: ["clockwork", "vanguard"],
    hp: 430,
    attack: 30,
    armor: 36,
    range: 185,
    attackInterval: 1.34,
    moveSpeed: 34,
    abilityName: "震地重炮",
    abilityDescription: "炮击敌人最密集处，造成范围伤害与眩晕。",
    shop: true,
  }),
  sui_cat: unit({
    id: "sui_cat",
    name: "小猫帽岁己",
    title: "后排主C",
    glyph: "猫",
    color: "#625070",
    accent: "#e8a8f4",
    tier: 4,
    cost: 4,
    traits: ["sui_forms", "assassin"],
    hp: 226,
    attack: 39,
    armor: 15,
    range: 50,
    attackInterval: 0.74,
    moveSpeed: 94,
    abilityName: "小猫拳",
    abilityDescription: "切入最远敌人，连续打出三记小猫拳并恢复造成伤害的生命。",
    portrait: "/images/materials/岁己SUI小猫帽带饼干岁紫色外套双马尾.png",
    portraitFocus: "top",
    shop: true,
  }),
  nagisa: unit({
    id: "nagisa",
    name: "米汀",
    title: "潮汐屏障",
    glyph: "汀",
    color: "#487b81",
    accent: "#91e4dc",
    tier: 4,
    cost: 4,
    traits: ["clockwork", "vanguard"],
    hp: 360,
    attack: 29,
    armor: 32,
    range: 55,
    attackInterval: 1.16,
    moveSpeed: 44,
    abilityName: "潮汐屏障",
    abilityDescription: "为全队提供护盾，并震晕身边的敌人。",
    portrait: "/images/livers/nagisa.png",
    portraitFocus: "top",
    shop: true,
  }),

  // 5 费：低概率出现的终局棋子，每一个都有改变战局的技能。
  dawn_sovereign: unit({
    id: "dawn_sovereign",
    name: "天穹裁决者",
    title: "连锁裁决",
    glyph: "裁",
    color: "#315f7d",
    accent: "#b9f1ff",
    tier: 5,
    cost: 5,
    traits: ["aegis", "ranger"],
    hp: 250,
    attack: 45,
    armor: 22,
    range: 260,
    attackInterval: 0.72,
    moveSpeed: 56,
    abilityName: "天穹裁决",
    abilityDescription: "向所有敌人释放递减连锁光束，并为友军套盾。",
    shop: true,
  }),
  solar_champion: unit({
    id: "solar_champion",
    name: "曜星战神",
    title: "毁阵重击",
    glyph: "曜",
    color: "#45647a",
    accent: "#ffe08b",
    tier: 5,
    cost: 5,
    traits: ["aegis", "brawler"],
    hp: 410,
    attack: 48,
    armor: 38,
    range: 58,
    attackInterval: 0.94,
    moveSpeed: 60,
    abilityName: "曜星坠击",
    abilityDescription: "砸向敌群造成高额范围伤害，眩晕并获得护盾。",
    shop: true,
  }),
  inferno_witch: unit({
    id: "inferno_witch",
    name: "焚世巫女",
    title: "终局法核",
    glyph: "劫",
    color: "#762f45",
    accent: "#ff8a75",
    tier: 5,
    cost: 5,
    traits: ["ember", "mystic"],
    hp: 218,
    attack: 41,
    armor: 12,
    range: 235,
    attackInterval: 1.05,
    moveSpeed: 52,
    abilityName: "末日星雨",
    abilityDescription: "对全体敌人降下陨火，并施加猛烈灼烧。",
    shop: true,
  }),
  sky_drake: unit({
    id: "sky_drake",
    name: "苍穹龙鹰",
    title: "残血弹幕",
    glyph: "龙",
    color: "#32634f",
    accent: "#8ff5bb",
    tier: 5,
    cost: 5,
    traits: ["wild", "ranger"],
    hp: 268,
    attack: 43,
    armor: 16,
    range: 255,
    attackInterval: 0.62,
    moveSpeed: 72,
    abilityName: "猎空风暴",
    abilityDescription: "连续发射六次追踪弹，优先攻击残血目标。",
    shop: true,
  }),
  void_reaper: unit({
    id: "void_reaper",
    name: "虚空终猎者",
    title: "连续处决",
    glyph: "终",
    color: "#422553",
    accent: "#dc7dff",
    tier: 5,
    cost: 5,
    traits: ["rift", "assassin"],
    hp: 232,
    attack: 52,
    armor: 18,
    range: 50,
    attackInterval: 0.66,
    moveSpeed: 104,
    abilityName: "三界绝命",
    abilityDescription: "依次斩击三名最虚弱的敌人，每次击杀都会回复能量。",
    shop: true,
  }),
  chrono_titan: unit({
    id: "chrono_titan",
    name: "时序泰坦",
    title: "全场停滞",
    glyph: "时",
    color: "#554f3a",
    accent: "#f4dc84",
    tier: 5,
    cost: 5,
    traits: ["clockwork", "brawler"],
    hp: 470,
    attack: 46,
    armor: 32,
    range: 62,
    attackInterval: 0.9,
    moveSpeed: 50,
    abilityName: "时序归零",
    abilityDescription: "伤害并长时间冻结全部敌人。",
    shop: true,
  }),
  biscuit_sui: unit({
    id: "biscuit_sui",
    name: "饼干岁",
    title: "饼干终结者",
    glyph: "饼",
    color: "#9a6a4c",
    accent: "#ffd28d",
    tier: 5,
    cost: 5,
    traits: ["sui_forms", "brawler"],
    hp: 420,
    attack: 44,
    armor: 34,
    range: 58,
    attackInterval: 0.92,
    moveSpeed: 58,
    abilityName: "饼干拳法",
    abilityDescription: "冲进敌人最密集处施展饼干拳法，造成范围伤害、眩晕并获得护盾。",
    portrait: "/images/materials/biscuit/饼干岁2.png",
    portraitFocus: "top",
    shop: true,
  }),

  rift_tyrant: unit({
    id: "rift_tyrant",
    name: "裂隙暴君",
    title: "终局首领",
    glyph: "王",
    color: "#501c45",
    accent: "#ff5dad",
    tier: 5,
    cost: 5,
    traits: [],
    hp: 1180,
    attack: 36,
    armor: 28,
    range: 75,
    attackInterval: 1.04,
    moveSpeed: 46,
    abilityName: "裂界冲击",
    abilityDescription: "冲击全场并眩晕所有敌人，半血后进入狂暴。",
    shop: false,
  }),
};

export const SHOP_UNITS: ShopUnitId[] = [...SHOP_UNIT_IDS];

export const STARTERS: StarterDefinition[] = [
  {
    id: "bastion",
    name: "壁垒协议",
    subtitle: "稳扎稳打",
    description: "携带曜盾卫士开局；基地生命 +4，所有护盾效果 +30%。",
    unit: "sun_guard",
    color: "#69d8ff",
  },
  {
    id: "blaze",
    name: "余烬协议",
    subtitle: "压血抢攻",
    description: "携带熔火刃开局；灼烧伤害 +40%，首次胜利额外获得 2 金币。",
    unit: "ember_blade",
    color: "#ff8058",
  },
  {
    id: "echo",
    name: "回响协议",
    subtitle: "灵活续航",
    description: "携带岚羽开局；荒灵吸血额外 +6%，初始金币 +1。",
    unit: "gale_archer",
    color: "#76e7ae",
  },
];

export const AUGMENTS: AugmentDefinition[] = [
  {
    id: "tempered",
    name: "回火装甲",
    kicker: "生存",
    description: "所有友军获得 16 护甲。",
    color: "#76cfff",
  },
  {
    id: "overclock",
    name: "预充能",
    kicker: "技能",
    description: "所有友军开战时额外获得 35 能量。",
    color: "#c58cff",
  },
  {
    id: "sharp_edge",
    name: "锐锋校准",
    kicker: "输出",
    description: "所有友军攻击力提高 15%。",
    color: "#ff986b",
  },
  {
    id: "momentum",
    name: "战斗惯性",
    kicker: "节奏",
    description: "所有友军攻击速度提高 18%。",
    color: "#f4d35e",
  },
  {
    id: "triage",
    name: "战地分诊",
    kicker: "续航",
    description: "每 2.5 秒治疗全部友军 3% 最大生命。",
    color: "#72e7a5",
  },
  {
    id: "payday",
    name: "风险投资",
    kicker: "经济",
    description: "立即获得 6 金币，之后每回合收入 +1。",
    color: "#ffd166",
  },
  {
    id: "execution",
    name: "弱点协议",
    kicker: "收割",
    description: "对生命低于 40% 的敌人造成 28% 额外伤害。",
    color: "#ff6b8a",
  },
  {
    id: "second_wind",
    name: "不屈回路",
    kicker: "容错",
    description: "每名友军首次低于 30% 生命时恢复 24% 最大生命。",
    color: "#88a7ff",
  },
];

export const WAVES: WaveDefinition[] = [
  {
    round: 1,
    name: "边缘侦察队",
    tag: "normal",
    description: "前排薄弱，适合熟悉站位。",
    modifier: 0.64,
    units: [{ id: "sun_guard" }, { id: "ember_blade" }],
  },
  {
    round: 2,
    name: "林地巡游团",
    tag: "normal",
    description: "苔甲保护后排，优先处理岚羽。",
    modifier: 0.75,
    units: [{ id: "mossback" }, { id: "gale_archer" }, { id: "cog_scribe" }],
  },
  {
    round: 3,
    name: "赤角突击队",
    tag: "normal",
    description: "冲阵者会打乱前线，分散站位可降低损失。",
    modifier: 0.88,
    units: [
      { id: "cinder_ram" },
      { id: "rift_brawler" },
      { id: "clock_gunner" },
      { id: "spark_mage" },
    ],
  },
  {
    round: 4,
    name: "黄铜火力网",
    tag: "elite",
    description: "巨像控前排，狙击手锁定远端单位。",
    modifier: 0.96,
    units: [
      { id: "brass_colossus" },
      { id: "gear_sniper" },
      { id: "spark_mage" },
      { id: "dawn_duelist" },
    ],
  },
  {
    round: 5,
    name: "荒棘猎团",
    tag: "normal",
    description: "祭司与蛮王续航很强，需要集火或切后。",
    modifier: 1,
    units: [
      { id: "thorn_brute" },
      { id: "mossback" },
      { id: "grove_mender" },
      { id: "void_oracle" },
      { id: "ash_dancer" },
    ],
  },
  {
    round: 6,
    name: "攻城序列",
    tag: "normal",
    description: "重炮惩罚抱团，月蚀牙会直扑后排。",
    modifier: 1.02,
    units: [
      { id: "siege_walker" },
      { id: "rift_warden" },
      { id: "prism_sage" },
      { id: "moonfang" },
      { id: "gear_sniper" },
    ],
  },
  {
    round: 7,
    name: "五系禁卫",
    tag: "elite",
    description: "精英战：五种威胁同时登场，检验阵容完整度。",
    modifier: 1.04,
    units: [
      { id: "rift_warden" },
      { id: "iron_dervish" },
      { id: "sun_phoenix" },
      { id: "void_oracle" },
      { id: "gear_sniper" },
      { id: "ash_dancer" },
    ],
  },
  {
    round: 8,
    name: "暴君降临",
    tag: "boss",
    description: "暴君携带双辅卫队；优先拆掉护盾与诅咒源。",
    modifier: 1,
    units: [{ id: "rift_tyrant" }, { id: "prism_sage" }, { id: "void_oracle" }],
  },
];

export const CAMPAIGN_ROUNDS = WAVES.length;

const ENDLESS_NAMES = [
  "回响突击群",
  "裂隙混编队",
  "失序远征军",
  "深层守望者",
] as const;

export const waveForRound = (round: number): WaveDefinition => {
  if (round <= WAVES.length) return WAVES[Math.max(0, round - 1)];

  const endlessRound = round - WAVES.length;
  const cycle = Math.floor((endlessRound - 1) / 5);
  const boss = endlessRound % 5 === 0;
  const elite = !boss && endlessRound % 3 === 0;
  const tag: WaveDefinition["tag"] = boss ? "boss" : elite ? "elite" : "normal";
  const unitCount = Math.min(8, 5 + Math.floor((endlessRound + 1) / 3));
  const minimumTier = Math.min(4, 2 + Math.floor(endlessRound / 5));
  const candidates = SHOP_UNITS.filter(
    (id) => UNIT_DEFS[id].tier >= minimumTier,
  );
  const units: WaveUnit[] = Array.from({ length: unitCount }, (_, index) => {
    const id = candidates[(round * 7 + index * 11 + cycle * 3) % candidates.length];
    const star: 1 | 2 | 3 =
      endlessRound >= 18 && index < 2
        ? 3
        : endlessRound >= 6 && index < 2 + Math.floor(endlessRound / 8)
          ? 2
          : 1;
    return { id, star };
  });
  if (boss) units[0] = { id: "rift_tyrant", star: cycle >= 3 ? 2 : 1 };

  return {
    round,
    name: boss
      ? `暴君回响 · ${cycle + 1}`
      : `${ENDLESS_NAMES[(endlessRound - 1) % ENDLESS_NAMES.length]} · ${endlessRound}`,
    tag,
    description: boss
      ? "无限首领战：暴君会随循环强化，保存阵型的同时准备爆发。"
      : elite
        ? "无限精英战：高费混编与升星单位同时出现。"
        : "无限挑战：敌军编成与强度将持续成长。",
    modifier: 1.06 + endlessRound * 0.035 + cycle * 0.035,
    units,
  };
};

export const PLAYER_LEVELS = [3, 4, 5, 6, 7, 8] as const;
export type PlayerLevel = (typeof PLAYER_LEVELS)[number];
export type ShopTierOdds = readonly [number, number, number, number, number];

interface PlayerLevelConfig {
  boardCap: number;
  upgradeCost: number | null;
  tierOdds: ShopTierOdds;
}

export const STARTING_PLAYER_LEVEL: PlayerLevel = 3;
export const MAX_PLAYER_LEVEL: PlayerLevel = 8;
export const bookLevelForPlayerLevel = (level: PlayerLevel) => level - 2;
export const PASSIVE_UPGRADE_DISCOUNT = 1;

export const PLAYER_LEVEL_CONFIG: Record<PlayerLevel, PlayerLevelConfig> = {
  3: { boardCap: 3, upgradeCost: 5, tierOdds: [75, 25, 0, 0, 0] },
  4: { boardCap: 4, upgradeCost: 9, tierOdds: [48, 38, 13, 1, 0] },
  5: { boardCap: 5, upgradeCost: 14, tierOdds: [30, 33, 26, 10, 1] },
  6: { boardCap: 6, upgradeCost: 20, tierOdds: [10, 20, 30, 29, 11] },
  7: { boardCap: 7, upgradeCost: 27, tierOdds: [5, 15, 29, 34, 17] },
  8: { boardCap: 8, upgradeCost: null, tierOdds: [2, 10, 23, 36, 29] },
};

export const tierOddsForLevel = (level: PlayerLevel) =>
  PLAYER_LEVEL_CONFIG[level].tierOdds;

export const upgradeCostForLevel = (level: PlayerLevel) =>
  PLAYER_LEVEL_CONFIG[level].upgradeCost;

export const SHOP_TIER_COUNTS = [1, 2, 3, 4, 5].map(
  (tier) => SHOP_UNITS.filter((id) => UNIT_DEFS[id].tier === tier).length,
);
