/* eslint-disable implicit-arrow-linebreak */

export const TRAIT_IDS = [
  "aegis",
  "ember",
  "wild",
  "rift",
  "clockwork",
  "vanguard",
  "ranger",
  "mystic",
  "brawler",
  "assassin",
] as const;

export type TraitId = (typeof TRAIT_IDS)[number];

export const SHOP_UNIT_IDS = [
  // 1 费
  "sun_guard",
  "ember_blade",
  "gale_archer",
  "rift_stalker",
  "cog_scribe",
  "mossback",
  // 2 费
  "rift_brawler",
  "spark_mage",
  "clock_gunner",
  "dawn_duelist",
  "grove_mender",
  "cinder_ram",
  // 3 费
  "brass_colossus",
  "ash_dancer",
  "thorn_brute",
  "void_oracle",
  "gear_sniper",
  "shade_reaver",
  // 4 费
  "sun_phoenix",
  "prism_sage",
  "moonfang",
  "rift_warden",
  "iron_dervish",
  "siege_walker",
  // 5 费
  "dawn_sovereign",
  "solar_champion",
  "inferno_witch",
  "sky_drake",
  "void_reaper",
  "chrono_titan",
] as const;

export type ShopUnitId = (typeof SHOP_UNIT_IDS)[number];
export type UnitId = ShopUnitId | "rift_tyrant";

export type StarterId = "bastion" | "blaze" | "echo";

export type AugmentId =
  | "tempered"
  | "overclock"
  | "sharp_edge"
  | "momentum"
  | "triage"
  | "payday"
  | "execution"
  | "second_wind";

export interface UnitDefinition {
  id: UnitId;
  name: string;
  title: string;
  glyph: string;
  color: string;
  accent: string;
  tier: 1 | 2 | 3 | 4 | 5;
  cost: number;
  traits: TraitId[];
  hp: number;
  attack: number;
  armor: number;
  range: number;
  attackInterval: number;
  moveSpeed: number;
  abilityName: string;
  abilityDescription: string;
  shop: boolean;
}

export interface TraitDefinition {
  id: TraitId;
  name: string;
  family: "阵营" | "职业";
  color: string;
  thresholds: readonly [2, 4, 6];
  description: string;
  bonuses: readonly [string, string, string];
}

export interface StarterDefinition {
  id: StarterId;
  name: string;
  subtitle: string;
  description: string;
  unit: ShopUnitId;
  color: string;
}

export interface AugmentDefinition {
  id: AugmentId;
  name: string;
  kicker: string;
  description: string;
  color: string;
}

export interface WaveUnit {
  id: UnitId;
  star?: 1 | 2 | 3;
}

export interface WaveDefinition {
  round: number;
  name: string;
  tag: "normal" | "elite" | "boss";
  description: string;
  modifier: number;
  units: WaveUnit[];
}

export const TRAITS: Record<TraitId, TraitDefinition> = {
  aegis: {
    id: "aegis",
    name: "曜甲",
    family: "阵营",
    color: "#66d7ff",
    thresholds: [2, 4, 6],
    description: "曜甲单位获得护甲与最大生命。",
    bonuses: [
      "+12 护甲、+7% 最大生命",
      "+25 护甲、+14% 最大生命",
      "+42 护甲、+23% 最大生命",
    ],
  },
  ember: {
    id: "ember",
    name: "余烬",
    family: "阵营",
    color: "#ff7657",
    thresholds: [2, 4, 6],
    description: "余烬单位的普攻施加三秒灼烧。",
    bonuses: [
      "灼烧造成 35% 攻击力伤害",
      "灼烧造成 65% 攻击力伤害",
      "灼烧造成 105% 攻击力伤害",
    ],
  },
  wild: {
    id: "wild",
    name: "荒灵",
    family: "阵营",
    color: "#70e1a0",
    thresholds: [2, 4, 6],
    description: "荒灵单位造成伤害时恢复生命。",
    bonuses: ["获得 8% 吸血", "获得 15% 吸血", "获得 24% 吸血"],
  },
  rift: {
    id: "rift",
    name: "裂隙",
    family: "阵营",
    color: "#c08bff",
    thresholds: [2, 4, 6],
    description: "裂隙单位擅长终结受伤目标。",
    bonuses: [
      "对半血目标 +15% 伤害",
      "对半血目标 +32% 伤害",
      "对半血目标 +55% 伤害",
    ],
  },
  clockwork: {
    id: "clockwork",
    name: "机巧",
    family: "阵营",
    color: "#e5bf68",
    thresholds: [2, 4, 6],
    description: "机巧单位获得攻速，普攻额外回复能量。",
    bonuses: [
      "+10% 攻速、每击 +4 能量",
      "+22% 攻速、每击 +8 能量",
      "+38% 攻速、每击 +14 能量",
    ],
  },
  vanguard: {
    id: "vanguard",
    name: "先锋",
    family: "职业",
    color: "#819eff",
    thresholds: [2, 4, 6],
    description: "先锋单位获得最大生命与护甲。",
    bonuses: [
      "+12% 生命、+8 护甲",
      "+25% 生命、+18 护甲",
      "+42% 生命、+32 护甲",
    ],
  },
  ranger: {
    id: "ranger",
    name: "游击",
    family: "职业",
    color: "#f2d15e",
    thresholds: [2, 4, 6],
    description: "游击单位获得攻击速度。",
    bonuses: ["+12% 攻速", "+26% 攻速", "+45% 攻速"],
  },
  mystic: {
    id: "mystic",
    name: "秘术",
    family: "职业",
    color: "#de87ff",
    thresholds: [2, 4, 6],
    description: "秘术单位更早、更频繁地释放技能。",
    bonuses: [
      "开战 +20 能量",
      "开战 +45、施法返还 8 能量",
      "开战 +70、施法返还 15 能量",
    ],
  },
  brawler: {
    id: "brawler",
    name: "斗阵",
    family: "职业",
    color: "#ffae57",
    thresholds: [2, 4, 6],
    description: "斗阵单位获得攻击力。",
    bonuses: ["+12% 攻击力", "+26% 攻击力", "+45% 攻击力"],
  },
  assassin: {
    id: "assassin",
    name: "夜袭",
    family: "职业",
    color: "#ff6fae",
    thresholds: [2, 4, 6],
    description: "夜袭单位开战跃向后排，并有概率暴击。",
    bonuses: ["15% 暴击率", "30% 暴击率", "50% 暴击率"],
  },
};

export const traitLevelForCount = (trait: TraitDefinition, count: number) =>
  trait.thresholds.filter((threshold) => count >= threshold).length;

const unit = (definition: UnitDefinition) => definition;

export const UNIT_DEFS: Record<UnitId, UnitDefinition> = {
  // 1 费：可靠的构筑零件，每个都能明确指向一条阵容路线。
  sun_guard: unit({
    id: "sun_guard",
    name: "曜盾卫士",
    title: "坚守前线",
    glyph: "盾",
    color: "#245f80",
    accent: "#7de2ff",
    tier: 1,
    cost: 1,
    traits: ["aegis", "vanguard"],
    hp: 245,
    attack: 16,
    armor: 30,
    range: 48,
    attackInterval: 1.12,
    moveSpeed: 52,
    abilityName: "折光壁垒",
    abilityDescription: "获得护盾，震击并短暂眩晕当前目标。",
    shop: true,
  }),
  ember_blade: unit({
    id: "ember_blade",
    name: "熔火刃",
    title: "近战爆发",
    glyph: "焰",
    color: "#7b2f2b",
    accent: "#ff8a5c",
    tier: 1,
    cost: 1,
    traits: ["ember", "brawler"],
    hp: 178,
    attack: 25,
    armor: 12,
    range: 50,
    attackInterval: 0.92,
    moveSpeed: 64,
    abilityName: "熔断横斩",
    abilityDescription: "横扫目标周围的敌人，并施加灼烧。",
    shop: true,
  }),
  gale_archer: unit({
    id: "gale_archer",
    name: "岚羽",
    title: "高速点射",
    glyph: "岚",
    color: "#245e4e",
    accent: "#7ef0bb",
    tier: 1,
    cost: 1,
    traits: ["wild", "ranger"],
    hp: 132,
    attack: 21,
    armor: 6,
    range: 225,
    attackInterval: 0.84,
    moveSpeed: 58,
    abilityName: "追风三矢",
    abilityDescription: "连续射出三支箭，优先追击残血敌人。",
    shop: true,
  }),
  rift_stalker: unit({
    id: "rift_stalker",
    name: "隙影斥候",
    title: "后排骚扰",
    glyph: "隙",
    color: "#493464",
    accent: "#c99cff",
    tier: 1,
    cost: 1,
    traits: ["rift", "assassin"],
    hp: 146,
    attack: 23,
    armor: 8,
    range: 48,
    attackInterval: 0.88,
    moveSpeed: 78,
    abilityName: "影隙突刺",
    abilityDescription: "闪至最虚弱的敌人身旁突刺，并获得小额护盾。",
    shop: true,
  }),
  cog_scribe: unit({
    id: "cog_scribe",
    name: "齿轮学徒",
    title: "能量干扰",
    glyph: "轮",
    color: "#4d4936",
    accent: "#e8ca75",
    tier: 1,
    cost: 1,
    traits: ["clockwork", "mystic"],
    hp: 138,
    attack: 18,
    armor: 8,
    range: 190,
    attackInterval: 1.08,
    moveSpeed: 48,
    abilityName: "回转电弧",
    abilityDescription: "电击两个敌人并削减其能量。",
    shop: true,
  }),
  mossback: unit({
    id: "mossback",
    name: "苔甲幼兽",
    title: "群体庇护",
    glyph: "苔",
    color: "#315b40",
    accent: "#80d792",
    tier: 1,
    cost: 1,
    traits: ["wild", "vanguard"],
    hp: 255,
    attack: 15,
    armor: 24,
    range: 48,
    attackInterval: 1.2,
    moveSpeed: 45,
    abilityName: "共生甲壳",
    abilityDescription: "治疗自己，并为最虚弱的友军提供护盾。",
    shop: true,
  }),

  // 2 费：开始提供反后排、控制和续航等战术答案。
  rift_brawler: unit({
    id: "rift_brawler",
    name: "裂隙猎手",
    title: "残血收割",
    glyph: "猎",
    color: "#4c3c72",
    accent: "#c4a1ff",
    tier: 2,
    cost: 2,
    traits: ["rift", "brawler"],
    hp: 205,
    attack: 29,
    armor: 14,
    range: 52,
    attackInterval: 1.02,
    moveSpeed: 76,
    abilityName: "相位猎杀",
    abilityDescription: "跃向生命比例最低的敌人，重创残血目标。",
    shop: true,
  }),
  spark_mage: unit({
    id: "spark_mage",
    name: "星火术士",
    title: "范围轰击",
    glyph: "星",
    color: "#593270",
    accent: "#e7a3ff",
    tier: 2,
    cost: 2,
    traits: ["ember", "mystic"],
    hp: 142,
    attack: 21,
    armor: 6,
    range: 205,
    attackInterval: 1.18,
    moveSpeed: 50,
    abilityName: "坠星火",
    abilityDescription: "轰击敌人最密集的区域，造成范围伤害与灼烧。",
    shop: true,
  }),
  clock_gunner: unit({
    id: "clock_gunner",
    name: "机巧枪手",
    title: "直线穿透",
    glyph: "铳",
    color: "#36566f",
    accent: "#92d7ff",
    tier: 2,
    cost: 2,
    traits: ["clockwork", "ranger"],
    hp: 158,
    attack: 22,
    armor: 12,
    range: 245,
    attackInterval: 0.72,
    moveSpeed: 48,
    abilityName: "超载贯射",
    abilityDescription: "发射贯穿战场的高能弹，惩罚站成一线的敌人。",
    shop: true,
  }),
  dawn_duelist: unit({
    id: "dawn_duelist",
    name: "晨锋决斗家",
    title: "锁定后排",
    glyph: "锋",
    color: "#315b78",
    accent: "#9ee8ff",
    tier: 2,
    cost: 2,
    traits: ["aegis", "assassin"],
    hp: 176,
    attack: 27,
    armor: 16,
    range: 50,
    attackInterval: 0.82,
    moveSpeed: 82,
    abilityName: "破晓决斗",
    abilityDescription: "突进至最远敌人，重击并短暂眩晕。",
    shop: true,
  }),
  grove_mender: unit({
    id: "grove_mender",
    name: "森灵祭司",
    title: "战地治疗",
    glyph: "愈",
    color: "#28644b",
    accent: "#79f2ad",
    tier: 2,
    cost: 2,
    traits: ["wild", "mystic"],
    hp: 158,
    attack: 16,
    armor: 9,
    range: 190,
    attackInterval: 1.22,
    moveSpeed: 46,
    abilityName: "生息回响",
    abilityDescription: "治疗生命比例最低的两名友军。",
    shop: true,
  }),
  cinder_ram: unit({
    id: "cinder_ram",
    name: "烬角冲阵者",
    title: "开团控制",
    glyph: "角",
    color: "#71382f",
    accent: "#ff9a64",
    tier: 2,
    cost: 2,
    traits: ["ember", "vanguard"],
    hp: 278,
    attack: 20,
    armor: 25,
    range: 50,
    attackInterval: 1.16,
    moveSpeed: 68,
    abilityName: "赤角冲锋",
    abilityDescription: "冲进敌群，震晕并灼烧落点附近的敌人。",
    shop: true,
  }),

  // 3 费：阵容中期核心，技能形态开始明显改变站位价值。
  brass_colossus: unit({
    id: "brass_colossus",
    name: "铜墙巨像",
    title: "群体控制",
    glyph: "岳",
    color: "#5f5435",
    accent: "#f2d276",
    tier: 3,
    cost: 3,
    traits: ["aegis", "vanguard"],
    hp: 350,
    attack: 22,
    armor: 38,
    range: 52,
    attackInterval: 1.32,
    moveSpeed: 38,
    abilityName: "山崩震荡",
    abilityDescription: "震晕周围敌人并获得护盾。",
    shop: true,
  }),
  ash_dancer: unit({
    id: "ash_dancer",
    name: "灰烬舞者",
    title: "多段切入",
    glyph: "舞",
    color: "#75334a",
    accent: "#ff829c",
    tier: 3,
    cost: 3,
    traits: ["ember", "assassin"],
    hp: 190,
    attack: 32,
    armor: 13,
    range: 50,
    attackInterval: 0.76,
    moveSpeed: 88,
    abilityName: "烬步连舞",
    abilityDescription: "穿梭攻击三名敌人，并沿途留下灼烧。",
    shop: true,
  }),
  thorn_brute: unit({
    id: "thorn_brute",
    name: "棘原蛮王",
    title: "吸血旋击",
    glyph: "棘",
    color: "#3b6547",
    accent: "#8be59c",
    tier: 3,
    cost: 3,
    traits: ["wild", "brawler"],
    hp: 286,
    attack: 31,
    armor: 20,
    range: 54,
    attackInterval: 0.98,
    moveSpeed: 60,
    abilityName: "荆棘风暴",
    abilityDescription: "横扫附近敌人，每命中一名敌人都会恢复生命。",
    shop: true,
  }),
  void_oracle: unit({
    id: "void_oracle",
    name: "虚界先知",
    title: "克制高血量",
    glyph: "卜",
    color: "#4e3569",
    accent: "#d0a0ff",
    tier: 3,
    cost: 3,
    traits: ["rift", "mystic"],
    hp: 172,
    attack: 25,
    armor: 10,
    range: 215,
    attackInterval: 1.12,
    moveSpeed: 50,
    abilityName: "虚蚀预言",
    abilityDescription: "诅咒最大生命最高的敌人，附加其最大生命伤害。",
    shop: true,
  }),
  gear_sniper: unit({
    id: "gear_sniper",
    name: "发条狙击手",
    title: "超远单点",
    glyph: "狙",
    color: "#47576a",
    accent: "#b4dcff",
    tier: 3,
    cost: 3,
    traits: ["clockwork", "ranger"],
    hp: 166,
    attack: 34,
    armor: 9,
    range: 285,
    attackInterval: 1.05,
    moveSpeed: 42,
    abilityName: "校准绝响",
    abilityDescription: "蓄力狙击最远敌人，造成高额单体伤害。",
    shop: true,
  }),
  shade_reaver: unit({
    id: "shade_reaver",
    name: "黯隙收割者",
    title: "技能重置",
    glyph: "黯",
    color: "#3e294f",
    accent: "#b96fff",
    tier: 3,
    cost: 3,
    traits: ["rift", "assassin"],
    hp: 182,
    attack: 33,
    armor: 12,
    range: 48,
    attackInterval: 0.86,
    moveSpeed: 92,
    abilityName: "黯影处决",
    abilityDescription: "重创最虚弱的敌人；击杀后立即回复大量能量。",
    shop: true,
  }),

  // 4 费：可以围绕其单独建立阵容的核心单位。
  sun_phoenix: unit({
    id: "sun_phoenix",
    name: "焚天鸟",
    title: "全场灼烧",
    glyph: "凰",
    color: "#7b3e2c",
    accent: "#ffd166",
    tier: 4,
    cost: 4,
    traits: ["ember", "ranger"],
    hp: 190,
    attack: 31,
    armor: 12,
    range: 225,
    attackInterval: 0.78,
    moveSpeed: 64,
    abilityName: "燎原羽雨",
    abilityDescription: "灼烧全部敌人，并恢复自身生命。",
    shop: true,
  }),
  prism_sage: unit({
    id: "prism_sage",
    name: "棱光贤者",
    title: "全队庇护",
    glyph: "棱",
    color: "#416580",
    accent: "#a9ecff",
    tier: 4,
    cost: 4,
    traits: ["aegis", "mystic"],
    hp: 205,
    attack: 25,
    armor: 18,
    range: 210,
    attackInterval: 1.08,
    moveSpeed: 48,
    abilityName: "万华折光",
    abilityDescription: "治疗全队、赋予护盾，并为友军补充能量。",
    shop: true,
  }),
  moonfang: unit({
    id: "moonfang",
    name: "月蚀牙",
    title: "后排连斩",
    glyph: "牙",
    color: "#315846",
    accent: "#8ff0c0",
    tier: 4,
    cost: 4,
    traits: ["wild", "assassin"],
    hp: 222,
    attack: 38,
    armor: 16,
    range: 50,
    attackInterval: 0.7,
    moveSpeed: 96,
    abilityName: "月下狩猎",
    abilityDescription: "扑向最远敌人连续撕咬，并恢复造成伤害的生命。",
    shop: true,
  }),
  rift_warden: unit({
    id: "rift_warden",
    name: "界门守望者",
    title: "团队护盾",
    glyph: "门",
    color: "#44365e",
    accent: "#c39cff",
    tier: 4,
    cost: 4,
    traits: ["rift", "vanguard"],
    hp: 405,
    attack: 27,
    armor: 34,
    range: 55,
    attackInterval: 1.24,
    moveSpeed: 42,
    abilityName: "界门封锁",
    abilityDescription: "为全队提供护盾，并震晕身边敌人。",
    shop: true,
  }),
  iron_dervish: unit({
    id: "iron_dervish",
    name: "铁律旋刃",
    title: "持续范围伤害",
    glyph: "旋",
    color: "#5a513c",
    accent: "#e7c66f",
    tier: 4,
    cost: 4,
    traits: ["clockwork", "brawler"],
    hp: 318,
    attack: 36,
    armor: 26,
    range: 58,
    attackInterval: 0.74,
    moveSpeed: 66,
    abilityName: "齿轮圆舞",
    abilityDescription: "高速旋转切割附近敌人，并立刻重置普攻。",
    shop: true,
  }),
  siege_walker: unit({
    id: "siege_walker",
    name: "攻城履带",
    title: "重炮控制",
    glyph: "炮",
    color: "#4a5260",
    accent: "#f0ca78",
    tier: 4,
    cost: 4,
    traits: ["clockwork", "vanguard"],
    hp: 430,
    attack: 30,
    armor: 36,
    range: 185,
    attackInterval: 1.34,
    moveSpeed: 34,
    abilityName: "震地重炮",
    abilityDescription: "炮击敌人最密集处，造成范围伤害与眩晕。",
    shop: true,
  }),

  // 5 费：低概率出现的终局棋子，每一个都有改变战局的技能。
  dawn_sovereign: unit({
    id: "dawn_sovereign",
    name: "天穹裁决者",
    title: "连锁裁决",
    glyph: "裁",
    color: "#315f7d",
    accent: "#b9f1ff",
    tier: 5,
    cost: 5,
    traits: ["aegis", "ranger"],
    hp: 250,
    attack: 45,
    armor: 22,
    range: 260,
    attackInterval: 0.72,
    moveSpeed: 56,
    abilityName: "天穹裁决",
    abilityDescription: "向所有敌人释放递减连锁光束，并为友军套盾。",
    shop: true,
  }),
  solar_champion: unit({
    id: "solar_champion",
    name: "曜星战神",
    title: "毁阵重击",
    glyph: "曜",
    color: "#45647a",
    accent: "#ffe08b",
    tier: 5,
    cost: 5,
    traits: ["aegis", "brawler"],
    hp: 410,
    attack: 48,
    armor: 38,
    range: 58,
    attackInterval: 0.94,
    moveSpeed: 60,
    abilityName: "曜星坠击",
    abilityDescription: "砸向敌群造成高额范围伤害，眩晕并获得护盾。",
    shop: true,
  }),
  inferno_witch: unit({
    id: "inferno_witch",
    name: "焚世巫女",
    title: "终局法核",
    glyph: "劫",
    color: "#762f45",
    accent: "#ff8a75",
    tier: 5,
    cost: 5,
    traits: ["ember", "mystic"],
    hp: 218,
    attack: 41,
    armor: 12,
    range: 235,
    attackInterval: 1.05,
    moveSpeed: 52,
    abilityName: "末日星雨",
    abilityDescription: "对全体敌人降下陨火，并施加猛烈灼烧。",
    shop: true,
  }),
  sky_drake: unit({
    id: "sky_drake",
    name: "苍穹龙鹰",
    title: "残血弹幕",
    glyph: "龙",
    color: "#32634f",
    accent: "#8ff5bb",
    tier: 5,
    cost: 5,
    traits: ["wild", "ranger"],
    hp: 268,
    attack: 43,
    armor: 16,
    range: 255,
    attackInterval: 0.62,
    moveSpeed: 72,
    abilityName: "猎空风暴",
    abilityDescription: "连续发射六次追踪弹，优先攻击残血目标。",
    shop: true,
  }),
  void_reaper: unit({
    id: "void_reaper",
    name: "虚空终猎者",
    title: "连续处决",
    glyph: "终",
    color: "#422553",
    accent: "#dc7dff",
    tier: 5,
    cost: 5,
    traits: ["rift", "assassin"],
    hp: 232,
    attack: 52,
    armor: 18,
    range: 50,
    attackInterval: 0.66,
    moveSpeed: 104,
    abilityName: "三界绝命",
    abilityDescription: "依次斩击三名最虚弱的敌人，每次击杀都会回复能量。",
    shop: true,
  }),
  chrono_titan: unit({
    id: "chrono_titan",
    name: "时序泰坦",
    title: "全场停滞",
    glyph: "时",
    color: "#554f3a",
    accent: "#f4dc84",
    tier: 5,
    cost: 5,
    traits: ["clockwork", "brawler"],
    hp: 470,
    attack: 46,
    armor: 32,
    range: 62,
    attackInterval: 0.9,
    moveSpeed: 50,
    abilityName: "时序归零",
    abilityDescription: "伤害并长时间冻结全部敌人。",
    shop: true,
  }),

  rift_tyrant: unit({
    id: "rift_tyrant",
    name: "裂隙暴君",
    title: "终局首领",
    glyph: "王",
    color: "#501c45",
    accent: "#ff5dad",
    tier: 5,
    cost: 5,
    traits: [],
    hp: 1180,
    attack: 36,
    armor: 28,
    range: 75,
    attackInterval: 1.04,
    moveSpeed: 46,
    abilityName: "裂界冲击",
    abilityDescription: "冲击全场并眩晕所有敌人，半血后进入狂暴。",
    shop: false,
  }),
};

export const SHOP_UNITS: ShopUnitId[] = [...SHOP_UNIT_IDS];

export const STARTERS: StarterDefinition[] = [
  {
    id: "bastion",
    name: "壁垒协议",
    subtitle: "稳扎稳打",
    description: "携带曜盾卫士开局；基地生命 +4，所有护盾效果 +30%。",
    unit: "sun_guard",
    color: "#69d8ff",
  },
  {
    id: "blaze",
    name: "余烬协议",
    subtitle: "压血抢攻",
    description: "携带熔火刃开局；灼烧伤害 +40%，首次胜利额外获得 2 金币。",
    unit: "ember_blade",
    color: "#ff8058",
  },
  {
    id: "echo",
    name: "回响协议",
    subtitle: "灵活续航",
    description: "携带岚羽开局；荒灵吸血额外 +6%，初始金币 +1。",
    unit: "gale_archer",
    color: "#76e7ae",
  },
];

export const AUGMENTS: AugmentDefinition[] = [
  {
    id: "tempered",
    name: "回火装甲",
    kicker: "生存",
    description: "所有友军获得 16 护甲。",
    color: "#76cfff",
  },
  {
    id: "overclock",
    name: "预充能",
    kicker: "技能",
    description: "所有友军开战时额外获得 35 能量。",
    color: "#c58cff",
  },
  {
    id: "sharp_edge",
    name: "锐锋校准",
    kicker: "输出",
    description: "所有友军攻击力提高 15%。",
    color: "#ff986b",
  },
  {
    id: "momentum",
    name: "战斗惯性",
    kicker: "节奏",
    description: "所有友军攻击速度提高 18%。",
    color: "#f4d35e",
  },
  {
    id: "triage",
    name: "战地分诊",
    kicker: "续航",
    description: "每 2.5 秒治疗全部友军 3% 最大生命。",
    color: "#72e7a5",
  },
  {
    id: "payday",
    name: "风险投资",
    kicker: "经济",
    description: "立即获得 6 金币，之后每回合收入 +1。",
    color: "#ffd166",
  },
  {
    id: "execution",
    name: "弱点协议",
    kicker: "收割",
    description: "对生命低于 40% 的敌人造成 28% 额外伤害。",
    color: "#ff6b8a",
  },
  {
    id: "second_wind",
    name: "不屈回路",
    kicker: "容错",
    description: "每名友军首次低于 30% 生命时恢复 24% 最大生命。",
    color: "#88a7ff",
  },
];

export const WAVES: WaveDefinition[] = [
  {
    round: 1,
    name: "边缘侦察队",
    tag: "normal",
    description: "前排薄弱，适合熟悉站位。",
    modifier: 0.64,
    units: [{ id: "sun_guard" }, { id: "ember_blade" }],
  },
  {
    round: 2,
    name: "林地巡游团",
    tag: "normal",
    description: "苔甲保护后排，优先处理岚羽。",
    modifier: 0.75,
    units: [{ id: "mossback" }, { id: "gale_archer" }, { id: "cog_scribe" }],
  },
  {
    round: 3,
    name: "赤角突击队",
    tag: "normal",
    description: "冲阵者会打乱前线，分散站位可降低损失。",
    modifier: 0.88,
    units: [
      { id: "cinder_ram" },
      { id: "rift_brawler" },
      { id: "clock_gunner" },
      { id: "spark_mage" },
    ],
  },
  {
    round: 4,
    name: "黄铜火力网",
    tag: "elite",
    description: "巨像控前排，狙击手锁定远端单位。",
    modifier: 0.96,
    units: [
      { id: "brass_colossus" },
      { id: "gear_sniper" },
      { id: "spark_mage" },
      { id: "dawn_duelist" },
    ],
  },
  {
    round: 5,
    name: "荒棘猎团",
    tag: "normal",
    description: "祭司与蛮王续航很强，需要集火或切后。",
    modifier: 1,
    units: [
      { id: "thorn_brute" },
      { id: "mossback" },
      { id: "grove_mender" },
      { id: "void_oracle" },
      { id: "ash_dancer" },
    ],
  },
  {
    round: 6,
    name: "攻城序列",
    tag: "normal",
    description: "重炮惩罚抱团，月蚀牙会直扑后排。",
    modifier: 1.02,
    units: [
      { id: "siege_walker" },
      { id: "rift_warden" },
      { id: "prism_sage" },
      { id: "moonfang" },
      { id: "gear_sniper" },
    ],
  },
  {
    round: 7,
    name: "五系禁卫",
    tag: "elite",
    description: "精英战：五种威胁同时登场，检验阵容完整度。",
    modifier: 1.04,
    units: [
      { id: "rift_warden" },
      { id: "iron_dervish" },
      { id: "sun_phoenix" },
      { id: "void_oracle" },
      { id: "gear_sniper" },
      { id: "ash_dancer" },
    ],
  },
  {
    round: 8,
    name: "暴君降临",
    tag: "boss",
    description: "暴君携带双辅卫队；优先拆掉护盾与诅咒源。",
    modifier: 1,
    units: [{ id: "rift_tyrant" }, { id: "prism_sage" }, { id: "void_oracle" }],
  },
];

export const BOARD_CAP_BY_ROUND = [3, 3, 4, 4, 5, 5, 6, 6];

export const tierOddsForRound = (
  round: number,
): [number, number, number, number, number] => {
  if (round <= 1) return [75, 25, 0, 0, 0];
  if (round === 2) return [60, 35, 5, 0, 0];
  if (round === 3) return [48, 38, 13, 1, 0];
  if (round === 4) return [38, 36, 21, 5, 0];
  if (round === 5) return [30, 33, 26, 10, 1];
  if (round === 6) return [22, 30, 30, 15, 3];
  if (round === 7) return [15, 25, 31, 23, 6];
  return [10, 20, 30, 29, 11];
};

export const SHOP_TIER_COUNTS = [1, 2, 3, 4, 5].map(
  (tier) => SHOP_UNITS.filter((id) => UNIT_DEFS[id].tier === tier).length,
);
