export type Choice = "press" | "pass";
export type ThemeId = "vtuber" | "everyday";
export type Perspective = "streamer" | "viewer" | "anyone";

export interface Question {
  id: string;
  version: number;
  theme: ThemeId;
  perspective: Perspective;
  tags: string[];
  gain: string;
  cost: string;
  source?: { date: string; time: string; note: string };
}

export const THEMES = [
  { id: "vtuber", name: "虚拟主播", subtitle: "直播间里的另一种可能" },
  { id: "everyday", name: "日常脑洞", subtitle: "生活偶尔也有隐藏选项" },
] as const;

export const TAGS: Record<string, string> = {
  inspiration: "直播原梗",
  daily: "直播日常",
  persona: "模型人设",
  collab: "联动关系",
  stage: "舞台梦想",
  fans: "观众关系",
  life: "生活交换",
  games: "游戏挑战",
  creation: "创作幕后",
  food: "吃喝脑洞",
  memory: "记忆时间",
};

export const QUESTIONS: Question[] = [
  {
    id: "vt-fame-and-essays",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["inspiration", "fans"],
    gain: "你成为了超受欢迎的虚拟主播。",
    cost: "你的粉丝每天都会写负面小作文，而且每一篇你都必须读完。",
    source: {
      date: "2026-09-07",
      time: "03:45:07",
      note: "岁己与犬绒联动中的即兴设问，整理改写。",
    },
  },
  {
    id: "vt-fifty-million",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["inspiration", "daily"],
    gain: "你立刻得到五千万元。",
    cost: "从此再也不能直播，包括换账号或换一个身份。",
    source: {
      date: "2026-09-07",
      time: "01:43:27",
      note: "联动介绍按钮玩法时的例题，补充换身份的边界。",
    },
  },
  {
    id: "vt-perfect-model",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["persona"],
    gain: "你免费拥有心目中最完美的 Live2D 模型。",
    cost: "它会实时显示你的真实表情，营业微笑和装作不在意都藏不住。",
  },
  {
    id: "vt-never-lag",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily"],
    gain: "你的直播永远不会掉帧、断流或设备故障。",
    cost: "每次开播的前十分钟，麦克风都会自动变成小学生变声器。",
  },
  {
    id: "vt-song-memory",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage"],
    gain: "任何歌听一遍，你就能完整唱下来，永远不会跑调。",
    cost: "唱到最动情的那句时，模型都会自动切成豆豆眼。",
  },
  {
    id: "vt-best-clip",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily", "fans"],
    gain: "你的每场直播都会诞生一个百万播放的切片。",
    cost: "爆火的永远是你最想剪掉的那一段。",
  },
  {
    id: "vt-collab-telepathy",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab"],
    gain: "你和联动搭档拥有完美默契，每个梗都能接住。",
    cost: "只要你们同时开口，两个人的声音就会互换一分钟。",
  },
  {
    id: "vt-offline-concert",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage"],
    gain: "你的个人线下演唱会座无虚席，所有观众都会唱你的歌。",
    cost: "返场曲必须是你出道时最想忘掉的那首黑历史原创。",
  },
  {
    id: "vt-new-outfit",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["persona"],
    gain: "每个月都有一套顶级画师设计的新衣装。",
    cost: "衣装主题只能由观众投票，你没有否决权。",
  },
  {
    id: "vt-game-master",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily"],
    gain: "任何游戏你都能一次通关，再难的 Boss 也不例外。",
    cost: "你的直播间从此只剩技术讨论，再也没有人陪你闲聊。",
  },
  {
    id: "vt-small-room",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["fans"],
    gain: "直播间的每个人都真心喜欢你，你也记得每个人。",
    cost: "这个直播间永远只能有一百名观众。",
  },
  {
    id: "vt-auto-reply",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["fans", "daily"],
    gain: "你能看清并回应每一条弹幕，不会再漏掉任何人。",
    cost: "每天的直播时长固定增加一小时，不能提前下播。",
  },
  {
    id: "vt-dream-duet",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab", "stage"],
    gain: "你可以和最憧憬的前辈合唱一首歌。",
    cost: "必须先在对方面前完整播放你三年前模仿 TA 的视频。",
  },
  {
    id: "vt-scheduled",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily"],
    gain: "无论多累，只要开播你就立刻恢复精神和好心情。",
    cost: "今后一年，所有直播都必须在早上六点开始。",
  },
  {
    id: "vt-poker-face",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["persona", "collab"],
    gain: "你在所有社交推理游戏里都能完美隐藏身份。",
    cost: "游戏以外只要说一句小谎，模型鼻子就会变长十秒。",
  },
  {
    id: "vt-brand-freedom",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily", "persona"],
    gain: "你每月都有稳定商单，收入足够支持全职创作。",
    cost: "每场直播都必须用广告腔说出固定的三句开场白。",
  },
  {
    id: "vt-same-day-debut",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab", "stage"],
    gain: "你和最好的朋友可以一起重新出道，所有筹备都有人负责。",
    cost: "原来账号的作品可以保留，但你们都不能告诉老观众新账号是谁。",
  },
  {
    id: "vt-3d-magic",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "persona"],
    gain: "你在家就能做电影级的 3D 演出，不用设备也不用排练。",
    cost: "演出里你只能以十厘米高的形象出现。",
  },
  {
    id: "vt-archive-safe",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily"],
    gain: "你的所有直播都有完美录播、字幕和时间轴。",
    cost: "你永远不能删除其中任何一次口误。",
  },
  {
    id: "vt-friend-success",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab"],
    gain: "你最好的联动搭档会实现 TA 所有的舞台梦想。",
    cost: "未来一年，你们的档期再也凑不出一场公开联动。",
  },
  {
    id: "vt-change-voice",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["persona"],
    gain: "你能随心切换任何喜欢的声线，唱歌也一样。",
    cost: "观众最喜欢的永远是你原本的声音，换声线时大家都会想念它。",
  },
  {
    id: "vt-live-translation",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab", "fans"],
    gain: "全世界的人都能无障碍听懂你的直播。",
    cost: "你说的所有谐音梗都会被一本正经地直译。",
  },
  {
    id: "vt-recognised",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans"],
    gain: "你最喜欢的主播会记住你的昵称和每一次到场。",
    cost: "TA 也会记住你每次说“去睡了”之后还在别的直播间出现。",
  },
  {
    id: "vt-forever-live",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans", "daily"],
    gain: "你推的主播永远不会停播，每周都有新直播。",
    cost: "每场直播都恰好在你睡着后一小时开始。",
  },
  {
    id: "vt-front-row",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["stage", "fans"],
    gain: "你永远能抢到你推的演出第一排。",
    cost: "现场镜头每次都会拍到你最陶醉的表情。",
  },
  {
    id: "vt-your-song",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["stage", "fans"],
    gain: "你推的主播会为你唱一次你最想听的歌。",
    cost: "这首歌必须由你先开麦唱一遍，不能放伴奏。",
  },
  {
    id: "vt-perfect-merch",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["persona", "fans"],
    gain: "你想要的周边永远不会缺货，也不会有质量问题。",
    cost: "每件周边上都会印着你第一次进入直播间时的昵称。",
  },
  {
    id: "vt-no-missed-live",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["daily", "fans"],
    gain: "你每天都能多出两小时，专门用来看喜欢的直播。",
    cost: "这两小时你只能看直播，不能发弹幕，也不能一心二用。",
  },
  {
    id: "vt-favourite-famous",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans"],
    gain: "你推的主播终于成为百万粉的大主播。",
    cost: "直播间太热闹，TA 几乎再也看不到你的弹幕。",
  },
  {
    id: "vt-meet-as-peer",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["collab"],
    gain: "你可以作为平等的创作搭档，和你推共同完成一部作品。",
    cost: "之后再看 TA 的直播，你很难找回最初那种单纯追星的心情。",
  },
  {
    id: "vt-spoiler-clip",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["daily", "fans"],
    gain: "你永远不会错过你推的任何名场面。",
    cost: "每次直播开始前，你都会被提前剧透这场最精彩的瞬间。",
  },
  {
    id: "vt-anniversary-letter",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans", "stage"],
    gain: "你推会在周年直播里，认真读完你写的祝福。",
    cost: "署名必须是你小时候用过的、最中二的网名。",
  },
  {
    id: "life-perfect-rest",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你每天睡四小时就能精神饱满。",
    cost: "你再也不会做梦，包括那些舍不得醒来的好梦。",
  },
  {
    id: "life-travel",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你可以免费去世界上任何地方旅行。",
    cost: "不能拍照、录像或直播，只能用自己的记忆留下风景。",
  },
  {
    id: "life-good-food",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "每一餐都有人做好你最想吃的菜。",
    cost: "每次都得当着厨师的面写一百字的真实食评。",
  },
  {
    id: "life-pause-time",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你每天都能暂停世界一小时，自由支配这段时间。",
    cost: "暂停时所有电子设备都不能用。",
  },
  {
    id: "life-find-things",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "所有丢失的东西都能立刻回到你手里。",
    cost: "每次取回时，都要向身边的人坦白一件自己的小糗事。",
  },
  {
    id: "life-sunday",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "每周都多一个完全不用工作的休息日。",
    cost: "这一天所有商店和外卖也都休息。",
  },
  {
    id: "vt-shadow-ensemble",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "creation"],
    gain: "只要你想好动作，就能拥有一支配合完美的 3D 伴舞团。",
    cost: "从此你每次演出的伴舞都只能是自己的复制体，不能邀请朋友替换。",
  },
  {
    id: "vt-scripted-perfection",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "creation"],
    gain: "你的每场演出都能保持排练时最好的状态，不会有任何失误。",
    cost: "演出开始后只能照稿唱跳，不能临时加一句话，也无法回应搭档的即兴发挥。",
  },
  {
    id: "vt-unseen-craft",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "creation"],
    gain: "你设计的舞台效果总能原样实现，观众也真心喜欢最终演出。",
    cost: "没有人会知道这些设计出自你手，哪怕你亲自解释，大家也记不住。",
  },
  {
    id: "vt-five-minute-retake",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "memory"],
    gain: "你可以把一次公开演出里失误的五分钟，重新演到满意为止。",
    cost: "被重演的那段时间里，观众的安慰和搭档的救场也会从所有记忆与录播中消失。",
  },
  {
    id: "vt-studio-mic",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "daily"],
    gain: "你的歌回永远拥有录音棚级的干净收音，不用再调试设备。",
    cost: "麦克风只会留下你的歌声，笑声、聊天和搭档临时加入的声音都传不出去。",
  },
  {
    id: "vt-open-voice-booth",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["creation", "persona"],
    gain: "你脑海中想要的任何配音效果，都能一次录到满意。",
    cost: "每次录音都必须有一位现实中的熟人坐在面前听完，不能独处录制。",
  },
  {
    id: "vt-raid-reserve",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["games", "collab"],
    gain: "你的固定队每次都能顺利通关最难的副本。",
    cost: "每场都必须有一名队友全程旁观、不能参与，而且只能由你决定是谁。",
  },
  {
    id: "vt-team-thoughts",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["games", "collab"],
    gain: "你能预先看见队友接下来十秒的行动，每次配合都准确无误。",
    cost: "游戏过程中，队友也会听到你心里真正想说、但还没开口的每一句吐槽。",
  },
  {
    id: "vt-tactical-director",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["games", "collab"],
    gain: "你总能安排出让固定队获胜的战术，大家也愿意听你指挥。",
    cost: "从此每局你都只能指挥、不能操作角色，自己的画面永远是旁观视角。",
  },
  {
    id: "vt-fearless-stories",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["games", "daily"],
    gain: "你玩恐怖游戏时再也不会害怕，也不会被突然出现的画面吓到。",
    cost: "你也永远无法从任何悬疑、惊悚作品里感受到紧张和刺激。",
  },
  {
    id: "vt-first-meeting-again",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab", "memory"],
    gain: "你和任何新搭档第一次联动，都能聊得自然又投缘。",
    cost: "联动结束后，你们都会忘记彼此的相处，下一次仍得从自我介绍开始。",
  },
  {
    id: "vt-unrecorded-collab",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["collab", "memory"],
    gain: "每个月你都能和最好的朋友凑出一晚完全不被打断的联动。",
    cost: "这些联动无法留下录播、切片、截图或文字转录，错过的人无法补看。",
  },
  {
    id: "vt-radio-for-everyone",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["stage", "fans"],
    gain: "你的每期音乐电台，都能让每位听众发现一首终身喜欢的歌。",
    cost: "歌单完全由系统决定，你永远不能在节目里分享自己最喜欢的那首。",
  },
  {
    id: "vt-instant-demo",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["creation", "stage"],
    gain: "你写下的每段旋律，都会立刻变成完整而动听的原创曲。",
    cost: "成品会立即以你的名字公开发布，不能藏起写给某个人的那首，也不能删除。",
  },
  {
    id: "vt-cold-pick-hit",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["creation", "fans"],
    gain: "你每次认真推荐的冷门作品，都会一夜爆红。",
    cost: "它爆红后，你自己就会彻底失去对它的兴趣，重看也找不回来。",
  },
  {
    id: "vt-silent-kitchen",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["food", "daily"],
    gain: "你的每场料理直播，都能做出看起来和吃起来都完美的一餐。",
    cost: "从备菜到出锅，你都不能说话、打字或用手势回应弹幕。",
  },
  {
    id: "vt-show-your-drafts",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["creation", "fans"],
    gain: "你的每次投稿都能准确传达创作本意，没有人会误读。",
    cost: "发布时必须附上完整创作过程，包括所有推翻的草稿、失败的尝试和临时犹豫。",
  },
  {
    id: "vt-unscheduled-freedom",
    version: 1,
    theme: "vtuber",
    perspective: "streamer",
    tags: ["daily", "fans"],
    gain: "你的所有直播时间都由自己决定，调整档期也不会影响收入。",
    cost: "观众永远收不到开播提醒，也看不到直播推荐，只有主动找来的人能看到你。",
  },
  {
    id: "vt-lost-archives",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["memory", "fans"],
    gain: "你能找回你推所有因设备或存储故障而遗失的旧录播。",
    cost: "必须按时间顺序看完这些录播，不能快进；全部看完前，你不能看 TA 的新直播。",
  },
  {
    id: "vt-first-listen-forever",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["stage", "memory"],
    gain: "你每次听你推唱歌，都会有第一次听见那首歌的惊喜。",
    cost: "唱完你就会忘记旋律，再也没法跟唱，反复听录音也记不住。",
  },
  {
    id: "vt-rehearsal-seat",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["stage", "creation"],
    gain: "你每次都能受邀旁听你推的彩排，还能当场提出建议。",
    cost: "相应的正式演出你就不能观看，现场、直播和录播都不行。",
  },
  {
    id: "vt-no-overlap",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["daily", "fans"],
    gain: "你最喜欢的两位主播，从此永远不会同时开播。",
    cost: "你每周只有固定的三个晚上能看到直播，其余时间只能看录播。",
  },
  {
    id: "vt-anonymous-welcome",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans"],
    gain: "你每次进入喜欢的直播间，主播都会真诚地叫出昵称欢迎你。",
    cost: "你在这里的所有发言都会匿名，无法让 TA 知道哪些话是你说的。",
  },
  {
    id: "vt-shared-headphones",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans", "collab"],
    gain: "你和最好的朋友不用设备或网络，也能随时同步看直播、听歌。",
    cost: "使用时会同步听见对方身边的一切声音，任何一方都不能单独静音。",
  },
  {
    id: "vt-worn-keepsake",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["persona", "fans"],
    gain: "你最珍惜的那件绝版周边，永远不会损坏或丢失。",
    cost: "从此每天出门都必须把它带在身上最显眼的位置，不能遮挡或留在家里。",
  },
  {
    id: "vt-uncredited-help",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["fans", "creation"],
    gain: "你写下的每一条认真建议，都能确实帮到你推的创作。",
    cost: "TA 永远不会知道建议来自你，也不会公开感谢这位匿名观众。",
  },
  {
    id: "vt-fan-project-vote",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["creation", "collab"],
    gain: "你发起的同人企划总能找到足够可靠的伙伴，绝不会烂尾。",
    cost: "成品只能按参与者的多数意见制作，即使你是发起人，也没有否决或返工权。",
  },
  {
    id: "vt-translated-voice",
    version: 1,
    theme: "vtuber",
    perspective: "viewer",
    tags: ["stage", "fans"],
    gain: "你能无延迟听懂所有海外直播和外语歌里的每一个细节。",
    cost: "你听到的声音会永久变成同一种新闻播音腔，包括唱歌和笑声。",
  },
  {
    id: "life-one-pot",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "food"],
    gain: "你只用一口小锅，就能做出任何自己想吃的菜。",
    cost: "做好的食物只有十分钟保持美味，过后再加热也恢复不了。",
  },
  {
    id: "life-clean-kitchen",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "food"],
    gain: "做饭后的碗筷和厨房会自动清洁，你永远不用收拾。",
    cost: "做饭时必须严格称量每种食材，连一撮盐也不能凭感觉放。",
  },
  {
    id: "life-unrepeatable-recipe",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "food"],
    gain: "无论你把哪些安全可食用的食材混在一起，都能做出好吃的料理。",
    cost: "你永远无法重复做出同一个味道，包括你最成功、最喜欢的那次。",
  },
  {
    id: "life-taste-of-memory",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["food", "memory"],
    gain: "你可以随时重现记忆里最怀念的一顿饭，味道分毫不差。",
    cost: "每重现一次，你就会忘记当时餐桌上的一句对话，自己无法挑选是哪句。",
  },
  {
    id: "life-lost-message",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "memory"],
    gain: "你能找回一条当年写给你、但没来得及看见的留言，知道它到底写了什么。",
    cost: "你现在珍藏的另一条留言会永远消失，连记忆也留不住，而且要由你亲自选出。",
  },
  {
    id: "life-borrowed-weekend",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "memory"],
    gain: "你可以把未来任意一个周末，提前到这周使用。",
    cost: "到了被借走的那两天，你必须照常工作或上学，不能再把它们挪走。",
  },
  {
    id: "life-skill-swap",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "creation"],
    gain: "你能立刻精通一门一直想学的兴趣技能。",
    cost: "你已经学会的另一项兴趣技能会退回初学者水平，交换哪项在按下后才揭晓。",
  },
  {
    id: "life-unmistakable-message",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你发出的每一条消息，都能准确表达本意，不会被误解。",
    cost: "每条消息都会延迟十分钟才送达，期间不能撤回或修改，紧急消息也一样。",
  },
  {
    id: "life-shared-day-off",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你与最在意的人，每周都能空出同一个完整休息日。",
    cost: "今后一年你们都不能临时改期，这一天的其他邀约只能拒绝。",
  },
  {
    id: "life-no-queue",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "今后一年，你为自己办事时都不用再排队。",
    cost: "每周必须抽出完整的两小时，替一位陌生人排队，而且不能找人代劳。",
  },
  {
    id: "life-photo-mood",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "memory"],
    gain: "你参加的每一张合照里，所有人都处在最好看的状态。",
    cost: "照片会同时显示每个人当时的真实心情，无法裁掉、遮住或修掉那一栏。",
  },
  {
    id: "life-one-person-home",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你能在任何城市免费拥有一间完全合心意的房间。",
    cost: "这会是你唯一能长期居住的地方，而任何人都不能来做客，也不能和你同住。",
  },
  {
    id: "life-perfect-recall",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life", "memory"],
    gain: "你能准确记住自己经历过的每件事，需要时随时回想。",
    cost: "那些尴尬、后悔和争吵也会一样清晰，时间再久也不会变淡。",
  },
  {
    id: "life-fastest-route",
    version: 1,
    theme: "everyday",
    perspective: "anyone",
    tags: ["life"],
    gain: "你每次出门，都能走上最快且绝不堵车的路线。",
    cost: "路上不会再偶遇熟人，也不会发现计划之外的小店和风景。",
  },
];

export function questionKey(question: Pick<Question, "id" | "version">) {
  return `${question.id}@${question.version}`;
}

export function findQuestion(id: unknown, version: unknown) {
  return QUESTIONS.find(
    (question) => question.id === id && question.version === version,
  );
}

export function filterQuestions(
  theme: ThemeId,
  tag: string,
  perspective: string,
) {
  return QUESTIONS.filter(
    (question) => question.theme === theme &&
      (tag === "all" || question.tags.includes(tag)) &&
      (perspective === "all" || question.perspective === perspective),
  );
}
