import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
// 1. 引入数据库和 headers
import pool from '@/lib/db';
import { headers } from 'next/headers';
import './globals.css';
import Analytics from '@/components/Analytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '岁己SUI应援站',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7443445828476112"
          crossOrigin="anonymous"
        />
      </head>
      <body className={inter.className}>
        {children}
        {/* 2. 插入统计组件，它会自动监听路由变化 */}
        <Analytics />
        {/* 2. 添加百度统计代码 */}
        <Script id="baidu-tongji" strategy="afterInteractive">
          {`
            var _hmt = _hmt || [];
            (function() {
              var hm = document.createElement("script");
              hm.src = "https://hm.baidu.com/hm.js?2d1e9bb0fa7e740ce41fe56c024bc0fc";
              var s = document.getElementsByTagName("script")[0];
              s.parentNode.insertBefore(hm, s);
            })();
          `}
        </Script>
      </body>
    </html>
  );
}
